### ISSUE TITLE
Make use of teachers comments to improve documentation

### ISSUE THREAD

**Issue by Adri-San** [Arquisoft/viade_es5a#47]
Documentation will be updated as well as enlarged with all the missed keys of the project. 

_**Whitebox Overall System**_ and _**Deployment View**_ diagrams will be reorganized and some more information about **_Solid Adapter_** will be added in order to explain its functional goal in the application.

**Comment by jaluma** [comment]
Fixed: CQRS and Deployment View

**Comment by ghost** [comment]
Fixed:  Building Block View
